# Generated by Django 3.1.5 on 2021-01-30 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authApi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLoginHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loginAt', models.DateTimeField(verbose_name='Login at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authApi.user')),
            ],
        ),
    ]
